// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAjNTI3SYADW8POl3xx-D4_n8VEXh4TRs',
    appId: '1:220291019857:web:c4ee54d2f5ba033dcfb470',
    messagingSenderId: '220291019857',
    projectId: 'news-app-e40c6',
    authDomain: 'news-app-e40c6.firebaseapp.com',
    storageBucket: 'news-app-e40c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM3XNVUrGfKJT1qfancOJ9Gb4ntPZNBVo',
    appId: '1:220291019857:android:78b378cabef2e1dacfb470',
    messagingSenderId: '220291019857',
    projectId: 'news-app-e40c6',
    storageBucket: 'news-app-e40c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsGlVJGZXDDwKcRKZhe-TTuFEfFbpTnC8',
    appId: '1:220291019857:ios:0ddfed70178f2d4ecfb470',
    messagingSenderId: '220291019857',
    projectId: 'news-app-e40c6',
    storageBucket: 'news-app-e40c6.appspot.com',
    iosClientId: '220291019857-vfk0te6a0p4lfcpe3nps04n5986543ar.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsAppAhmedOthmanAlhalwagy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsGlVJGZXDDwKcRKZhe-TTuFEfFbpTnC8',
    appId: '1:220291019857:ios:7fc83b3cfad67968cfb470',
    messagingSenderId: '220291019857',
    projectId: 'news-app-e40c6',
    storageBucket: 'news-app-e40c6.appspot.com',
    iosClientId: '220291019857-t0n5t51b91n8ic8nh9v701n3ahijtcrh.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsAppAhmedOthmanAlhalwagy.RunnerTests',
  );
}
